services:
  sshesame:
    build:
      context: ./sshesame
      dockerfile: Dockerfile
    volumes:
      - sshesame-data:/data/sshesame
    networks:
      honeypot_net:
        ipv4_address: 192.168.125.40
    ports:
      - "2221:2022"

  cowrie:
    build:
      context: ./cowrie
      dockerfile: docker/Dockerfile
    volumes:
      - cowrie-data:/data/cowrie
    networks:
      honeypot_net:
        ipv4_address: 192.168.125.30
    ports:
      - "2222:2222"


  debian:
    build:
      context: ./debian
      dockerfile: Dockerfile
    container_name: debian_host
    hostname: debian
    command: /usr/sbin/sshd -D
    ports:
      - "2224:22"
    networks:
      honeypot_net:
        ipv4_address: 192.168.125.90

  prober:
    image: prober
    # Comment out the line below to run on the honeypot network.
    # network_mode: "host"
    container_name: prober
    hostname: prober
    build:
      context: ./prober
      dockerfile: Dockerfile
    command: python3 /prober/src/probe.py
    environment:
      - GATEWAY_MAC=aa:bb:cc:dd:ee:ff
    working_dir: /prober/src
    volumes:
      - type: bind
        source: ./prober/src
        target: /prober/src
    # Comment out the 'networks' option below to run in network mode 'host'.
    networks:
      honeypot_net:
        ipv4_address: 192.168.125.10

  honeytrap:
    image: honeytrap/honeytrap:latest
    networks:
      honeypot_net:
        ipv4_address: 192.168.125.44
    ports:
      - "2225:8022"

  heralding:
      build:
        context: ./heralding
        dockerfile: Dockerfile
      volumes:
        - heralding-data:/data/heralding
      networks:
        honeypot_net:
          ipv4_address: 192.168.125.42
      ports:
        - "2223:22"
networks:
  honeypot_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.125.0/24
    driver_opts:
      com.docker.network.bridge.name: honeypots

volumes:
  sshesame-data:
  cowrie-data:
  heralding-data:
  honeytrap-data: