services:
  sshesame:
    build:
      context: ./sshesame
      dockerfile: Dockerfile
    volumes:
      - sshesame-data:/data/sshesame
    networks:
        honeypot_net:
          ipv4_address: 192.168.125.40
    ports:
      - "2221:2022"

  cowrie:
    build:
      context: ./cowrie
      dockerfile: docker/Dockerfile
    volumes:
      - cowrie-data:/data/cowrie
    networks:
      honeypot_net:
        ipv4_address: 192.168.125.30
    ports:
      - "2222:2222"


  debian:
    build:
      context: ./debian
      dockerfile: Dockerfile
    container_name: debian_host
    hostname: debian
    command: /usr/sbin/sshd -D
    ports:
      - "2224:22"
    networks:
      honeypot_net:
        ipv4_address: 192.168.125.90

  prober:
    container_name: prober
    hostname: prober
    build:
      context: ./prober
      dockerfile: Dockerfile
    command: python3 /prober/src/probe.py
    networks:
      honeypot_net:
        ipv4_address: 192.168.125.10
    working_dir:
      /prober/src
    volumes:
      - type: bind
        source: ./prober/src
        target: /prober/src

  honeytrap:
    image: honeytrap/honeytrap:latest
    networks:
      honeypot_net:
        ipv4_address: 192.168.125.44
    ports:
      - "8022:8022"
  heralding:
      build:
        context: ./heralding
        dockerfile: Dockerfile
      volumes:
        - heralding-data:/data/heralding
      networks:
        honeypot_net:
          ipv4_address: 192.168.125.42
      ports:
        - "8080:80"
networks:
  honeypot_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.125.0/24
    driver_opts:
      com.docker.network.bridge.name: honeypots

volumes:
  sshesame-data:
  cowrie-data:
  heralding-data: